apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aporeto-console-cluster-role-{{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aporeto-console-role-binding-{{ .Release.Namespace }}
  namespace: {{ .Values.apps.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aporeto-console-cluster-role-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: aporeto-console
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aporeto-console
  namespace: {{ .Release.Namespace }}
{{- if .Values.imagePullSecret }}
imagePullSecrets:
  - name: {{.Values.imagePullSecret }}
{{- end }}
